French translation
andyholmes/valent pull request #387
Opened 2023-03-04 16:34 UTC by VxlerieUwU

2023-03-04 19:28 UTC, andyholmes requested changes
LGTM, except for the conflict markers. Thanks!

2023-03-04 19:28 UTC, andyholmes commented on po/fr.po
> +>>>>>>> d9df43a (Added french translation)
```suggestion
<<<<<<< HEAD
msgstr "Éxecuter des commandes personnalisées"
=======
msgstr "Exécuter des commandes personnalisées"
>>>>>>> d9df43a (Added french translation)
```

Looks like this got caught up in a rebase. I'm not sure which is correct though, it's been years :slightly_smiling_face:

2023-03-04 19:28 UTC, andyholmes commented on po/fr.po
> +>>>>>>> d9df43a (Added french translation)
Also here.

2023-03-05 12:12 UTC, VxlerieUwU commented on po/fr.po
> +>>>>>>> d9df43a (Added french translation)
Both are done

2023-03-05 12:13 UTC, VxlerieUwU commented
Thanks for letting me know! Everything should be cleaned up now

2023-03-05 20:06 UTC, andyholmes approved these changes

2023-03-05 20:07 UTC, merged